# Setup
title:               Theo Chemel
tagline:             ''
description:         'Student by day, maker by night.'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Theo Chemel
  email:             theo@chemel.net

# Gems
plugins:
  - jekyll-paginate
