# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly. But not supported.
permalink: /:year/:month/:day/:title/
relative_permalink: false
encoding: utf-8

# Excerpt separator
excerpt_separator: <!--more-->

# Setup
title:               alexpaciorkowski.com
tagline:             ''
description:         '...'
url:                 https://alex-paciorkowski.github.io
baseurl:             ''
paginate:            5
paginate_path:       "/page:num" 


# About/contact
author:
  name:              Alex Paciorkowski
  url:               tba
  email:             tba

# Custom vars
version:             1.0.0
