# Setup
title:               dondon
tagline:             'blog'
description:         'Today I Learned'
url:                 https://dondon17.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              DOWOON KIM
  url:               https://github.com/dondon17
  contact:
    email:           qwerqw889@ajou.ac.kr
    github:          https://github.com/dondon17
    facebook:        https://www.facebook.com/25dons

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
