# Setup
title:               Gardens Between
tagline:             'irene_hong@outlook.com'
description:         '<h5 id="sidebar-welcome">Welcome</h5><br> This is a personal blog where I write things as a tech learner. Feel free to reach me anytime at irene_hong@outlook.com.'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Caifei Hong
  url:               https://github.com/irene-hong
  email:             irene_hong@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
time:             2021
update:           September
