# Setup
title:               Gardens Between
tagline:             'irene_hong@outlook.com'
description:         'Welcome!<br> This is a personal blog where I write things as a tech learner. Feel free to reach me at irene_hong@outlook.com.'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Caifei Hong
  url:               https://github.com/irene-hong
  email:             irene_hong@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
