# Site settings
title: Power in the Book
header-img: img/home-bg.jpg
email: admin@powerinthebook.com
copyright_name: Matthew Watkins
description: "There is a power in the book which will begin to flow into your lives the moment you begin a serious study of the book. "
baseurl: ""
url: "http://powerinthebook.com"
twitter_username: #powerinthebook
github_username:  #powerinthebook
facebook_username:  #powerinthebook
email_username:  #admin@powerinthebook.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
include: [ "_pages" ]
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [ jekyll-paginate, jekyll-feed ]
