# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
excerpt_separator: <!--more-->

# Setup
title:               alexpaciorkowski.com
tagline:             'a blog'
description:         'A blog on a number of subjects...'
url:                 tba
baseurl:             ''
paginate:            5
paginate_path:       "/page:num" 

# About/contact
author:
  name:              Alex Paciorkowski
  url:               tba
  email:             tba

# Custom vars
version:             1.0.0
