# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Recent thoughts.
tagline:             'A blog'
description:         '"The time has come," the Walrus said, "To talk of many things."'
url:                 #http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yini Shi
  url:               #https://twitter.com/mdo
  email:             yini.shi@gmail.com

# Custom vars
version:             1.0.0
