# Setup
title:               40 Hadis
tagline:             "Risale-i Nur'dan Kırk Hadis"
description:         "Risale-i Nur'da geçen hadislerden derlenmiş Kırk Hadis"
url:                 https://40hadis.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              40 Hadis
  url:               https://40hadis.github.io/
  email:             incomes.oculars_0y@icloud.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
