# Setup
title:               Theo Chemel
tagline: CNC, Electronics, and Software Projects.
description:         'Student / maker / hustler.'
url: 'https://theo.chemel.net'
baseurl:             '/'
paginate:            1
permalink:           pretty

# About/contact
author:
  name:              Theo Chemel
  email:             theo@chemel.net

# Gems
plugins:
  - jekyll-paginate
