# Setup
title:               Gireesh's Data Science Blog
tagline:             'The notes that I take while learning Data Science'
description:         'The notes that I take while learning Data Science'
url:                 https://gireeshs22.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Gireesh Sundaram
  url:               https://twitter.com/GireeshS22
  email:             sun.gireesh@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
