# Permalinks
permalink:           pretty

# Setup
title:               Hunter Loftis
tagline:             'Notes to self'
description:         'Notes to future me from <a href="https://twitter.com/hunterloftis" target="_blank">@hunterloftis</a>.'
url:                 https://hunterloftis.github.io
baseurl:             'https://hunterloftis.github.io'
paginate:            5
gems:                [jekyll-paginate]

# About/contact
author:
  name:              Hunter Loftis
  url:               https://twitter.com/hunterloftis

# Custom vars
version:             1.0.0