---
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: pretty
#relative_permalinks: true

# Setup
title: 'Ladies First!'
tagline: 'an annotated digital edition'
description: An annotated digital edition created with <a href="https://readux.ecds.emory.edu/">Readux</a>
url:
baseurl: ''

gems:
 - jekyll-sitemap

# About/contact
author:
  name: An Author
  url:
  email:
  twitter:

# Custom vars
version: 0.7

# readux export specifics
homepage_image: https://readux.ecds.emory.edu/books/emory:7sr72/pages/emory:gmrpr/single-page/

show_annotation_author: true
source_info:
  title: '"Ladies first!" a novel'
  author: 'Verdenal, Dominique François, Mrs.'
  date: '1896'
  url: https://readux.ecds.emory.edu/books/emory:7sr72/
  pdf_url: https://readux.ecds.emory.edu/books/emory:7sr72/pdf/#page=2
  via_readux: true

publication_info:
  title: '"Ladies first!" a novel, an annotated digital edition'
  date: '2016'
  author: 'Verdenal, Dominique François, Mrs.'
  editors:
    - "Tater, Anne O."
  tei_xml: tei.xml

# optional: set thumbnail page size to tune page browse display
image_size:
  page:
    width: 695
    height: 1000
  thumbnail:
    width: 208
    height: 300
  small-thumbnail:
    width: 69
    height: 100

collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/

defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
