# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Hi, I'm Rene
tagline:             Software Engineer
description:         'Backend Software Engineer'
url:                 https://github.com/renaynay/
baseurl:             'https://rene.sh'
paginate:            5

# About/contact
author:
  name:              Rene
  url:               https://github.com/renaynay/
  email:             renelubov.dev@gmail.com

# Custom vars
version:             1.0.0
