# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Hieu Nguyen's Blog
tagline:             'Easy Peasy Lemon Squeezy'
description:         'Bog about programming.'
url:                 https://hieunguyentrung.com
enforce_ssl:         hieunguyentrung.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hieu Nguyen
  url:               http://hieunguyentrung.com
  email:             nhieu92@gmail.com

# Custom vars
version:             1.0.0
