# Setup
title:               Lanyon
tagline:             "Doing my best to spread God's love to everyone"
description:         'A blog sharing for sharing the things of the heart'
url:                 https://rileylanyon.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Riley
  url:               #
  email:             #

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             #1.1.0
google_analytics_id: #UA-XXXX-Y
