# Dependencies
markdown:         redcarpet
highlighter:      true
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Arash
tagline:          'A Jekyll theme'
description:      'Collection of stories'
url:              http://arashThr.github.io

author:
  name:           'Arash Thr'
  url:            https://twitter.com/arashThr

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/arashThr/
