# Setup
title:               Theo Chemel
tagline:
description:         'Student / maker / hustler.'
url: 'https://theochemel.github.io'
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Theo Chemel
  email:             theo@chemel.net

# Gems
plugins:
  - jekyll-paginate
