# Setup
title:               payvision development
tagline:             'House of engineers'
description:         ''
url:                 https://leonardopoza.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Payvision Development
  url:               https://payvision.com
  email:             l.poza@payvision.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
