# Setup
title:               dondon
tagline:             'blog'
description:         '오늘보다 나은 내일이 되길...🙏🏻'
url:                 https://dondon17.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
logo:                '/public/apple-touch-icon-precomposed.png'

# About/contact
author:
  name:              DOWOON KIM
  url:               https://github.com/dondon17
  contact:
    email:           qwerqw889@ajou.ac.kr
    github:          https://github.com/dondon17
    facebook:        https://www.facebook.com/25dons
    instagram:       https://www.instagram.com/25dons

# Gems
plugins:
  - jekyll-paginate

# Custom vars
mathjax: true
google_analytics_token: ''
google_analytics_id: #UA-XXXX-Y

category_dir: category/
tag_dir: tag/
