# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:      misc/tech/musings
tagline:    'notebook for projects, problems and solutions'
description:    'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:        http://misctechmusings.com
baseurl:    https://github.com/p0rkjello/misctechmusings.com/
paginate:   5

# About/contact
author:
  name:     Andrew Bounds
  url:      https://twitter.com/p0rkjello
  email:    asbounds@gmail.com

# Custom vars
version:  1.0.0
