# Setup
title:               Caifei's Blog
tagline:             'Welcome to my personal website!'
description:         'Welcome to my personal website!'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Caifei Hong
  url:               https://github.com/irene-hong
  email:             irene_hong@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
