# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Acne Cure Zone Blog
tagline:          'Cures, Discussion, and Acne Anectodes'
description:      'Acne Cure Zone is a place where we discuss what has worked for us to clear and cure our acne problems. This is where admins will post their cures and any exceptional content from others who wish to have it published outside of *the zone.*'
url:              http://acnecurezone.com/cures

author:
  name:           'Michael Aslanian'
  url:            https://discourse.acnecurezone.com/users/mike/activity

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/acnecurezone/cures
