# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Atmanic
tagline:             '七日谈'
description:         '狂躁症患者的自我救赎.'
url:                 http://atmanic.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jim Jia
  url:               https://twitter.com/jl1987
  email:             linchia1987@gmail.com

# Custom vars
version:             1.0.0
