# Setup
title:               xiangdangsheng
tagline:             ''
description:         'Keeping track of the social/economical/political problems of South Korea.'
url:                 https://dlrjsldlfma.github.io/xiangdangsheng
baseurl:             ''
paginate:            10
permalink:           pretty

# About/contact
author:
  name:              dlrjsldlfma

# Gems
plugins:
  - jekyll-paginate
