# Setup
title:               Sharing His Love
tagline:             "Doing my best to spread God's love to everyone"
description:         "A blog for sharing the things that bring God's love."
url:                 https://love-of-God-and-of-all-men.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Riley
  url:               #
  email:             #

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             #1.1.0
google_analytics_id: #UA-XXXX-Y
