# Setup
title:               Shaukat Ibrahim
tagline:             
description:         
url:                
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shaukat Ibrahim
  url:               https://twitter.com/mdo
  email:             ibrash@furman.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.0.1
google_analytics_id: #UA-XXXX-Y
