# Setup
title:               Theo Chemel
tagline:             ''
description:         'Student by day, maker by night.'
url: 'https://theochemel.github.io/'
baseurl:             'https://theochemel.github.io/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Theo Chemel
  email:             theo@chemel.net

# Gems
plugins:
  - jekyll-paginate
