# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Alessio Periloso's Novels
tagline:             ''
description:         ''
url:                 http://periloso.github.io
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Alessio Periloso
  url:               https://periloso.it
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
