# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Power in the Book
tagline:             'A Book of Mormon blog'
description:         'A Book of Mormon blog'
url:                 http:/powerintheword.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Matthew Watkins
  url:               http://powerintheword.com
  email:             admin@powerintheword.com

# Custom vars
version:             1.0.0

# Gems
gems:
  - jekyll-paginate