# Setup
title:               Caife's Blog
tagline:             'irene_hong@outlook.com'
description:         'Caifei's Blog <br> Welcome to my personal website!'
# description:         '<img src="/images/avatar_rabbit.png" alt="avatar"> Caifei's Blog <br> Welcome to my personal website!'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Caifei Hong
  url:               https://github.com/irene-hong
  email:             irene_hong@outlook.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
