# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Chrispen Shumba
tagline:             'A data scientist at DXC Technology'
description:         '"In God I trust, all others must bring data". Follow me on <a href="https://twitter.com/chrispenlion?ref_src=twsrc%5Etfw" target="_blank">@chrispenlion</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
