# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            trap9.io
tagline:          'signals uninterupted'
description:      'The blog about cosmic radiation effects.'
url:              http://trap9.io
baseurl:          'http://trap9.io/'
paginate:         5

author:
  name:           'Jiri Zoth'
  url:            https://twitter.com/jzoaka

# Custom vars
version:          1.0.0

github:
  repo:
