# Setup
title:               Tomato
tagline:             '토마토는 맛있어'
description:         '백엔드 개발자 꿈나무의 블로그입니다.'
url:                 https://ssseungzz.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Seunghyeon-Kim
  url:               
  email:             ssseungzz7@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
