# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Srajan Garg
tagline:             'Computer Scientist in the making'
description:         'Programming & StarCraft & Pizza'
url:                 http://srajangarg.github.io/
paginate:            100

# About/contact
author:
  name:              Srajan Garg
  url:               http://srajangarg.github.io
  email:             srajan.garg@gmail.com

# Custom vars
version:             1.0.0
