# Setup
title:               Processamento Digital de Imagem - Exercícios
tagline:             ' Com OpenCV e C++'
description:         'Página reservada para a apresentação de soluções para os exercícios propostos na disciplina de Processamento Digital de Imagens - DCA0445, no curso de Engenharia Mecatrônica na UFRN'

# description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 'https://wesleywagner.github.io'
baseurl:             '/blog_PDI'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Wesley Wagner Varela Souza
  #url:               https://github.com/WesleyWagner
  email:             wesley.souza.016@ufrn.edu.br

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
