# Setup
title:               Langgo
tagline:             'Langgo blog'
description:         'Coding poetry and distance.'
url:                 http://blog.langgo.co
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Langwan
  url:               http://blog.langgo.co
  email:             langwanluo@126.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
