# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:           pretty
# relative_permalinks: true

# Setup
title:               liamOS
tagline:             'An iOS development blog'
description:         ''
url:                 https://liamnichols.github.io
baseurl:             ''
paginate:            5

# Gems
gems: [jekyll-paginate]

# About/contact
author:
  name:              Liam Nichols
  url:               https://twitter.com/liamnichols_
  email:             liam.nichols.ln@gmail.com
